# Generated by Django 5.0.6 on 2024-05-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.CharField(default='white', max_length=10),
        ),
    ]
