# Generated by Django 5.0.6 on 2024-06-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_time_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='white_time_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
