# Generated by Django 5.0.6 on 2024-06-02 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_black_time_remaining_game_white_time_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='game',
            name='black_time_remaining',
            field=models.IntegerField(default=14400),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='game',
            name='result',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='white_time_remaining',
            field=models.IntegerField(default=1440),
        ),
    ]
