# Generated by Django 5.0.6 on 2024-06-02 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_game_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black_time_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='game',
            name='white_time_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
