# Generated by Django 5.0.6 on 2024-06-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_black_time_remaining_alter_game_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='endgame',
            field=models.CharField(default='', max_length=100),
        ),
    ]
