# Generated by Django 5.0.6 on 2024-06-05 18:59

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_endgame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='start_time',
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='maximum_players',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='minimum_players',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.IntegerField(default=10, help_text='Minutes after creation'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
