# Generated by Django 5.0.6 on 2024-06-05 19:12

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_tournament_start_time_tournament_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
