# Generated by Django 5.0.6 on 2024-06-05 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_remove_tournament_players_tournament_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='start_minutes',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
