# Generated by Django 5.0.6 on 2024-06-05 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_tournament_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tournament',
            name='increment',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.round'),
        ),
    ]
