# Generated by Django 5.0.6 on 2024-06-05 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_tournament_duration_tournament_increment_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.tournament'),
        ),
    ]
