# Generated by Django 5.0.6 on 2024-06-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_game_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
