# Generated by Django 5.0.6 on 2024-06-06 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_alter_tournament_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo', models.IntegerField(default=1200)),
                ('games_white', models.IntegerField(default=0)),
                ('games_black', models.IntegerField(default=0)),
                ('wins_white', models.IntegerField(default=0)),
                ('wins_black', models.IntegerField(default=0)),
                ('losses_white', models.IntegerField(default=0)),
                ('losses_black', models.IntegerField(default=0)),
                ('draws_white', models.IntegerField(default=0)),
                ('draws_black', models.IntegerField(default=0)),
                ('tournaments_participated', models.IntegerField(default=0)),
                ('tournaments_won', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
