# Generated by Django 5.0.6 on 2024-06-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.IntegerField(default=0),
        ),
    ]
