# Generated by Django 5.0.6 on 2024-06-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_profile_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
